[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#161412"
textColor = "#F1EDE4"
primaryColor = "#E0651F"
borderColor = "#6B6454"
showSidebarBorder = true
baseRadius = "small"
font = "sans-serif"
headingFont = "serif"
codeFont = "monospace"
chartCategoricalColors = ["#E0651F", "#F1EDE4", "#9A9384", "#6B6454", "#161412"]
